version: 2.1

orbs:
  cypress: cypress-io/cypress@3.1.1

workflows:
  build:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --headless
      - deploy:
          requires:
            - cypress/run

jobs:
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            # Set up Heroku git remotes
            git remote add heroku https://heroku:${HEROKU_API_KEY}@git.heroku.com/tddah-fe.git

            # Push changes to Heroku
            git push heroku main
